language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r20.0.1-linux.tgz
  - tar -zxf android-sdk_r20.0.1-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  # use ~/builds/[Github username]/[project]/android-sdk-linux
  - export ANDROID_HOME=~/builds/remomueller/tasktracker-android/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.)
  # Currently:
  #   1- Android SDK Tools, revision 20.0.3
  #   2- Android SDK Platform-tools, revision 14
  #   4- SDK Platform Android 4.1, API 16, revision 2
  #  10- SDK Platform Android 2.3.3, API 10, revision 2
  - android list sdk
  - android update sdk --filter 1,2,4 --no-ui --force
